server.port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/myStudentConsumer
  rabbitmq:
    host: localhost
    port: 5675
    username: guest
    password: guest
    virtual-host: /
    ssl:
      enabled: false
    eager-initializer: true
  cloud:
    function:
      definition: consumerstudentadd
    stream:
      bindings:
        consumerstudentadd-in-0:
          destination: edu
          group: student.add.queue
          contentType: application/json
          binder: rabbit
          consumer:
            # Retry Mechanism Configuration
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-max-interval: 10000
            back-off-multiplier: 2.0
            republish-delivery-attempts: true

      rabbit:
        bindings:
          consumerstudentadd-in-0:
            consumer:
              acknowledge-mode: AUTO
              declare-exchange: false
              bind-queue: true
              binding-routing-key: saumrit.edu.student.add

              # DLQ Configuration
              auto-bind-dlq: true
              republish-to-dlq: true
              dead-letter-exchange: edu.DLX
              dead-letter-routing-key: student.add.queue.dlq
              dlq-name-suffix: .dlq



springdoc:
  swagger-ui:
    path: "/swagger-ui.html"